import type { WeddingExperienceSettings } from "@/src/types/wedding";

export const defaultExperienceSettings: WeddingExperienceSettings = {
  cover: {
    kicker: "Trân trọng kính mời",
    brideName: "Vũ Bình",
    connector: "&",
    groomName: "Thành Long",
    note: "Cùng mở thiệp và chung vui với hai gia đình",
    buttonText: "Mở thiệp",
    backgroundEnabled: false,
    backgroundAlt: "Ảnh nền mở thiệp",
    background: {
      positionX: 50,
      positionY: 50,
      zoom: 1,
      fitMode: "cover",
      backgroundColor: "#ffffff",
    },
    overlayColor: "#1d2d25",
    overlayOpacity: 0.28,
    blurPx: 0,
    alignment: "center",
    nameSize: "balanced",
    logoMode: "monogram",
    monogramText: "B & L",
    logoAlt: "Biểu trưng Vũ Bình và Thành Long",
    logoSize: "medium",
  },
  music: {
    enabled: true,
    src: "/music/wedding-theme.wav",
    title: "Giai điệu ngày vui",
    volume: 0.28,
    loop: true,
    autoplayAfterOpen: true,
  },
  youtube: {
    enabled: true,
    url: "https://youtu.be/t-uuZb5PrUs",
    title: "Bản nhạc chúng mình yêu thích",
    description: "Video chỉ phát khi bạn chủ động bấm xem.",
  },
  countdown: {
    backgroundEnabled: false,
    backgroundAlt: "Ảnh nền lịch cưới",
    background: {
      positionX: 50,
      positionY: 50,
      zoom: 1,
      fitMode: "cover",
      backgroundColor: "#ffffff",
    },
    overlayColor: "#17251f",
    overlayOpacity: 0.36,
    showCalendar: true,
    showLunarDate: true,
    showTime: true,
    showCountdown: true,
    markerStyle: "heart",
  },
  albumLayout: "spotlight",
  wishLayout: "elegant",
  allowGuestSideSelection: false,
};
